#!/bin/bash
### BEGIN INIT INFO
# Provides:          bulldog
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Check if a website is reachable
# Description:       Bulldog is an amazing hunting dog that checks for you a list of URLs and warns you by email if one of them returns a http code that is not 200.
### END INIT INFO

. /lib/lsb/init-functions

NAME=bulldog
DAEMON=/usr/bin/$NAME
CONFIG=/etc/$NAME
PIDFILE=/var/run/$NAME.pid

case "$1" in
  start)
    log_daemon_msg "Starting" "$NAME"
    if start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- -config $CONFIG ; then
      log_end_msg 0
    else
      log_end_msg 1
    fi
    ;;
  stop)
    log_daemon_msg "Stopping" "$NAME"
    if start-stop-daemon --stop --quiet --pidfile $PIDFILE ; then
      log_end_msg 0
    else
      log_end_msg 1
    fi
    ;;
  restart|force-reload)
    log_daemon_msg "Restarting" "$NAME"
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE &> /dev/null
    sleep 1
    if start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- -config $CONFIG ; then
      log_end_msg 0
    else
      log_end_msg 1
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 2
    ;;
esac

exit 0
