.TH man 1 "31 Oct 2017" "0.2.0" "Bulldog"
.SH NAME
Bulldog \- the http checker
.SH DESCRIPTION
Bulldog is an amazing hunting dog that checks for you a list of URLs and warns you by email if one of them returns a http code that is not 200.
.SH SYNOPSIS
bulldog [options]
.SH OPTIONS
.TP
.BR \-1
Perform URLs checks only one time.
.TP
.BR \-config " " string
Path to ini config for using in go flags. May be relative to the current executable path.
.TP
.BR \-f " " string
File that contains the urls to check each per line.
.TP
.BR \-gmail " " string
Gmail account. If this is present send email using the Gmail smtp server. Use -pass flag to specify the Gmail account password. If this flag is empty send email using mail command line program.
.TP
.BR \-logfile " " string
Logfile path. If empty logs on stdout.
.TP
.BR \-pass " " string
Gmail account password. Only relevant when using -gmail flag.
.TP
.BR \-quiet
Disable logging.
.TP
.BR \-s " " int
Seconds to sleep between a complete URLs check to another. (default 60)
.TP
.BR \-se " " int
Seconds to sleep between a complete URLs check to another if a check has failed. (default 600)
.TP
.BR \-t " " int
Check request timeout in seconds. (default 10)
.TP
.BR \-to " " string
When a check fails send an email on this email address. If is empty the email alert is disabled.
.TP
.BR \-urls " " value
Comma-separated list of URLs to check.
.TP
.BR \-v
Print version.
.SH AUTHOR
Enrico Pilotto (epilotto@gmx.com)
